name: GitHub Actions Build and Deploy Demo
on: [push]
# on:
#   push:
#     branches:
#       - vite
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install and Build 
      run: |
        yarn
        yarn test
        yarn build:app
          
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages
        folder: docs
